// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_contact_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_contact_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_contact_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_contact_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_contact_2eproto;
namespace contact {
class Add_Request;
struct Add_RequestDefaultTypeInternal;
extern Add_RequestDefaultTypeInternal _Add_Request_default_instance_;
class Add_Request_Phone;
struct Add_Request_PhoneDefaultTypeInternal;
extern Add_Request_PhoneDefaultTypeInternal _Add_Request_Phone_default_instance_;
class Add_Response;
struct Add_ResponseDefaultTypeInternal;
extern Add_ResponseDefaultTypeInternal _Add_Response_default_instance_;
}  // namespace contact
PROTOBUF_NAMESPACE_OPEN
template<> ::contact::Add_Request* Arena::CreateMaybeMessage<::contact::Add_Request>(Arena*);
template<> ::contact::Add_Request_Phone* Arena::CreateMaybeMessage<::contact::Add_Request_Phone>(Arena*);
template<> ::contact::Add_Response* Arena::CreateMaybeMessage<::contact::Add_Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace contact {

enum Add_Request_Phone_PhoneType : int {
  Add_Request_Phone_PhoneType_Mobile_Phone = 0,
  Add_Request_Phone_PhoneType_TELEPHONE = 1,
  Add_Request_Phone_PhoneType_Add_Request_Phone_PhoneType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Add_Request_Phone_PhoneType_Add_Request_Phone_PhoneType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Add_Request_Phone_PhoneType_IsValid(int value);
constexpr Add_Request_Phone_PhoneType Add_Request_Phone_PhoneType_PhoneType_MIN = Add_Request_Phone_PhoneType_Mobile_Phone;
constexpr Add_Request_Phone_PhoneType Add_Request_Phone_PhoneType_PhoneType_MAX = Add_Request_Phone_PhoneType_TELEPHONE;
constexpr int Add_Request_Phone_PhoneType_PhoneType_ARRAYSIZE = Add_Request_Phone_PhoneType_PhoneType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Add_Request_Phone_PhoneType_descriptor();
template<typename T>
inline const std::string& Add_Request_Phone_PhoneType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Add_Request_Phone_PhoneType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Add_Request_Phone_PhoneType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Add_Request_Phone_PhoneType_descriptor(), enum_t_value);
}
inline bool Add_Request_Phone_PhoneType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Add_Request_Phone_PhoneType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Add_Request_Phone_PhoneType>(
    Add_Request_Phone_PhoneType_descriptor(), name, value);
}
// ===================================================================

class Add_Request_Phone final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contact.Add_Request.Phone) */ {
 public:
  inline Add_Request_Phone() : Add_Request_Phone(nullptr) {}
  ~Add_Request_Phone() override;
  explicit PROTOBUF_CONSTEXPR Add_Request_Phone(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Add_Request_Phone(const Add_Request_Phone& from);
  Add_Request_Phone(Add_Request_Phone&& from) noexcept
    : Add_Request_Phone() {
    *this = ::std::move(from);
  }

  inline Add_Request_Phone& operator=(const Add_Request_Phone& from) {
    CopyFrom(from);
    return *this;
  }
  inline Add_Request_Phone& operator=(Add_Request_Phone&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Add_Request_Phone& default_instance() {
    return *internal_default_instance();
  }
  static inline const Add_Request_Phone* internal_default_instance() {
    return reinterpret_cast<const Add_Request_Phone*>(
               &_Add_Request_Phone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Add_Request_Phone& a, Add_Request_Phone& b) {
    a.Swap(&b);
  }
  inline void Swap(Add_Request_Phone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Add_Request_Phone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Add_Request_Phone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Add_Request_Phone>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Add_Request_Phone& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Add_Request_Phone& from) {
    Add_Request_Phone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Add_Request_Phone* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contact.Add_Request.Phone";
  }
  protected:
  explicit Add_Request_Phone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Add_Request_Phone_PhoneType PhoneType;
  static constexpr PhoneType Mobile_Phone =
    Add_Request_Phone_PhoneType_Mobile_Phone;
  static constexpr PhoneType TELEPHONE =
    Add_Request_Phone_PhoneType_TELEPHONE;
  static inline bool PhoneType_IsValid(int value) {
    return Add_Request_Phone_PhoneType_IsValid(value);
  }
  static constexpr PhoneType PhoneType_MIN =
    Add_Request_Phone_PhoneType_PhoneType_MIN;
  static constexpr PhoneType PhoneType_MAX =
    Add_Request_Phone_PhoneType_PhoneType_MAX;
  static constexpr int PhoneType_ARRAYSIZE =
    Add_Request_Phone_PhoneType_PhoneType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  PhoneType_descriptor() {
    return Add_Request_Phone_PhoneType_descriptor();
  }
  template<typename T>
  static inline const std::string& PhoneType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PhoneType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PhoneType_Name.");
    return Add_Request_Phone_PhoneType_Name(enum_t_value);
  }
  static inline bool PhoneType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      PhoneType* value) {
    return Add_Request_Phone_PhoneType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kNumberFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string number = 1;
  void clear_number();
  const std::string& number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_number();
  PROTOBUF_NODISCARD std::string* release_number();
  void set_allocated_number(std::string* number);
  private:
  const std::string& _internal_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_number(const std::string& value);
  std::string* _internal_mutable_number();
  public:

  // .contact.Add_Request.Phone.PhoneType type = 2;
  void clear_type();
  ::contact::Add_Request_Phone_PhoneType type() const;
  void set_type(::contact::Add_Request_Phone_PhoneType value);
  private:
  ::contact::Add_Request_Phone_PhoneType _internal_type() const;
  void _internal_set_type(::contact::Add_Request_Phone_PhoneType value);
  public:

  // @@protoc_insertion_point(class_scope:contact.Add_Request.Phone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr number_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contact_2eproto;
};
// -------------------------------------------------------------------

class Add_Request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contact.Add_Request) */ {
 public:
  inline Add_Request() : Add_Request(nullptr) {}
  ~Add_Request() override;
  explicit PROTOBUF_CONSTEXPR Add_Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Add_Request(const Add_Request& from);
  Add_Request(Add_Request&& from) noexcept
    : Add_Request() {
    *this = ::std::move(from);
  }

  inline Add_Request& operator=(const Add_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Add_Request& operator=(Add_Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Add_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const Add_Request* internal_default_instance() {
    return reinterpret_cast<const Add_Request*>(
               &_Add_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Add_Request& a, Add_Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Add_Request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Add_Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Add_Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Add_Request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Add_Request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Add_Request& from) {
    Add_Request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Add_Request* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contact.Add_Request";
  }
  protected:
  explicit Add_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Add_Request_Phone Phone;

  // accessors -------------------------------------------------------

  enum : int {
    kPhoneNumbsersFieldNumber = 3,
    kNameFieldNumber = 1,
    kAgeFieldNumber = 2,
  };
  // repeated .contact.Add_Request.Phone phone_numbsers = 3;
  int phone_numbsers_size() const;
  private:
  int _internal_phone_numbsers_size() const;
  public:
  void clear_phone_numbsers();
  ::contact::Add_Request_Phone* mutable_phone_numbsers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone >*
      mutable_phone_numbsers();
  private:
  const ::contact::Add_Request_Phone& _internal_phone_numbsers(int index) const;
  ::contact::Add_Request_Phone* _internal_add_phone_numbsers();
  public:
  const ::contact::Add_Request_Phone& phone_numbsers(int index) const;
  ::contact::Add_Request_Phone* add_phone_numbsers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone >&
      phone_numbsers() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 age = 2;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:contact.Add_Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone > phone_numbsers_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t age_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contact_2eproto;
};
// -------------------------------------------------------------------

class Add_Response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contact.Add_Response) */ {
 public:
  inline Add_Response() : Add_Response(nullptr) {}
  ~Add_Response() override;
  explicit PROTOBUF_CONSTEXPR Add_Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Add_Response(const Add_Response& from);
  Add_Response(Add_Response&& from) noexcept
    : Add_Response() {
    *this = ::std::move(from);
  }

  inline Add_Response& operator=(const Add_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Add_Response& operator=(Add_Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Add_Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const Add_Response* internal_default_instance() {
    return reinterpret_cast<const Add_Response*>(
               &_Add_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Add_Response& a, Add_Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Add_Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Add_Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Add_Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Add_Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Add_Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Add_Response& from) {
    Add_Response::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Add_Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contact.Add_Response";
  }
  protected:
  explicit Add_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kErrDescFieldNumber = 3,
    kOkFieldNumber = 2,
  };
  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // string err_desc = 3;
  void clear_err_desc();
  const std::string& err_desc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_err_desc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_err_desc();
  PROTOBUF_NODISCARD std::string* release_err_desc();
  void set_allocated_err_desc(std::string* err_desc);
  private:
  const std::string& _internal_err_desc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_err_desc(const std::string& value);
  std::string* _internal_mutable_err_desc();
  public:

  // bool ok = 2;
  void clear_ok();
  bool ok() const;
  void set_ok(bool value);
  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);
  public:

  // @@protoc_insertion_point(class_scope:contact.Add_Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr err_desc_;
    bool ok_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contact_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Add_Request_Phone

// string number = 1;
inline void Add_Request_Phone::clear_number() {
  _impl_.number_.ClearToEmpty();
}
inline const std::string& Add_Request_Phone::number() const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.Phone.number)
  return _internal_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Add_Request_Phone::set_number(ArgT0&& arg0, ArgT... args) {
 
 _impl_.number_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contact.Add_Request.Phone.number)
}
inline std::string* Add_Request_Phone::mutable_number() {
  std::string* _s = _internal_mutable_number();
  // @@protoc_insertion_point(field_mutable:contact.Add_Request.Phone.number)
  return _s;
}
inline const std::string& Add_Request_Phone::_internal_number() const {
  return _impl_.number_.Get();
}
inline void Add_Request_Phone::_internal_set_number(const std::string& value) {
  
  _impl_.number_.Set(value, GetArenaForAllocation());
}
inline std::string* Add_Request_Phone::_internal_mutable_number() {
  
  return _impl_.number_.Mutable(GetArenaForAllocation());
}
inline std::string* Add_Request_Phone::release_number() {
  // @@protoc_insertion_point(field_release:contact.Add_Request.Phone.number)
  return _impl_.number_.Release();
}
inline void Add_Request_Phone::set_allocated_number(std::string* number) {
  if (number != nullptr) {
    
  } else {
    
  }
  _impl_.number_.SetAllocated(number, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.number_.IsDefault()) {
    _impl_.number_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contact.Add_Request.Phone.number)
}

// .contact.Add_Request.Phone.PhoneType type = 2;
inline void Add_Request_Phone::clear_type() {
  _impl_.type_ = 0;
}
inline ::contact::Add_Request_Phone_PhoneType Add_Request_Phone::_internal_type() const {
  return static_cast< ::contact::Add_Request_Phone_PhoneType >(_impl_.type_);
}
inline ::contact::Add_Request_Phone_PhoneType Add_Request_Phone::type() const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.Phone.type)
  return _internal_type();
}
inline void Add_Request_Phone::_internal_set_type(::contact::Add_Request_Phone_PhoneType value) {
  
  _impl_.type_ = value;
}
inline void Add_Request_Phone::set_type(::contact::Add_Request_Phone_PhoneType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:contact.Add_Request.Phone.type)
}

// -------------------------------------------------------------------

// Add_Request

// string name = 1;
inline void Add_Request::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Add_Request::name() const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Add_Request::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contact.Add_Request.name)
}
inline std::string* Add_Request::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:contact.Add_Request.name)
  return _s;
}
inline const std::string& Add_Request::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Add_Request::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Add_Request::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Add_Request::release_name() {
  // @@protoc_insertion_point(field_release:contact.Add_Request.name)
  return _impl_.name_.Release();
}
inline void Add_Request::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contact.Add_Request.name)
}

// int32 age = 2;
inline void Add_Request::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t Add_Request::_internal_age() const {
  return _impl_.age_;
}
inline int32_t Add_Request::age() const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.age)
  return _internal_age();
}
inline void Add_Request::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void Add_Request::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:contact.Add_Request.age)
}

// repeated .contact.Add_Request.Phone phone_numbsers = 3;
inline int Add_Request::_internal_phone_numbsers_size() const {
  return _impl_.phone_numbsers_.size();
}
inline int Add_Request::phone_numbsers_size() const {
  return _internal_phone_numbsers_size();
}
inline void Add_Request::clear_phone_numbsers() {
  _impl_.phone_numbsers_.Clear();
}
inline ::contact::Add_Request_Phone* Add_Request::mutable_phone_numbsers(int index) {
  // @@protoc_insertion_point(field_mutable:contact.Add_Request.phone_numbsers)
  return _impl_.phone_numbsers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone >*
Add_Request::mutable_phone_numbsers() {
  // @@protoc_insertion_point(field_mutable_list:contact.Add_Request.phone_numbsers)
  return &_impl_.phone_numbsers_;
}
inline const ::contact::Add_Request_Phone& Add_Request::_internal_phone_numbsers(int index) const {
  return _impl_.phone_numbsers_.Get(index);
}
inline const ::contact::Add_Request_Phone& Add_Request::phone_numbsers(int index) const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.phone_numbsers)
  return _internal_phone_numbsers(index);
}
inline ::contact::Add_Request_Phone* Add_Request::_internal_add_phone_numbsers() {
  return _impl_.phone_numbsers_.Add();
}
inline ::contact::Add_Request_Phone* Add_Request::add_phone_numbsers() {
  ::contact::Add_Request_Phone* _add = _internal_add_phone_numbsers();
  // @@protoc_insertion_point(field_add:contact.Add_Request.phone_numbsers)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone >&
Add_Request::phone_numbsers() const {
  // @@protoc_insertion_point(field_list:contact.Add_Request.phone_numbsers)
  return _impl_.phone_numbsers_;
}

// -------------------------------------------------------------------

// Add_Response

// string uuid = 1;
inline void Add_Response::clear_uuid() {
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& Add_Response::uuid() const {
  // @@protoc_insertion_point(field_get:contact.Add_Response.uuid)
  return _internal_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Add_Response::set_uuid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.uuid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contact.Add_Response.uuid)
}
inline std::string* Add_Response::mutable_uuid() {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:contact.Add_Response.uuid)
  return _s;
}
inline const std::string& Add_Response::_internal_uuid() const {
  return _impl_.uuid_.Get();
}
inline void Add_Response::_internal_set_uuid(const std::string& value) {
  
  _impl_.uuid_.Set(value, GetArenaForAllocation());
}
inline std::string* Add_Response::_internal_mutable_uuid() {
  
  return _impl_.uuid_.Mutable(GetArenaForAllocation());
}
inline std::string* Add_Response::release_uuid() {
  // @@protoc_insertion_point(field_release:contact.Add_Response.uuid)
  return _impl_.uuid_.Release();
}
inline void Add_Response::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  _impl_.uuid_.SetAllocated(uuid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contact.Add_Response.uuid)
}

// bool ok = 2;
inline void Add_Response::clear_ok() {
  _impl_.ok_ = false;
}
inline bool Add_Response::_internal_ok() const {
  return _impl_.ok_;
}
inline bool Add_Response::ok() const {
  // @@protoc_insertion_point(field_get:contact.Add_Response.ok)
  return _internal_ok();
}
inline void Add_Response::_internal_set_ok(bool value) {
  
  _impl_.ok_ = value;
}
inline void Add_Response::set_ok(bool value) {
  _internal_set_ok(value);
  // @@protoc_insertion_point(field_set:contact.Add_Response.ok)
}

// string err_desc = 3;
inline void Add_Response::clear_err_desc() {
  _impl_.err_desc_.ClearToEmpty();
}
inline const std::string& Add_Response::err_desc() const {
  // @@protoc_insertion_point(field_get:contact.Add_Response.err_desc)
  return _internal_err_desc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Add_Response::set_err_desc(ArgT0&& arg0, ArgT... args) {
 
 _impl_.err_desc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contact.Add_Response.err_desc)
}
inline std::string* Add_Response::mutable_err_desc() {
  std::string* _s = _internal_mutable_err_desc();
  // @@protoc_insertion_point(field_mutable:contact.Add_Response.err_desc)
  return _s;
}
inline const std::string& Add_Response::_internal_err_desc() const {
  return _impl_.err_desc_.Get();
}
inline void Add_Response::_internal_set_err_desc(const std::string& value) {
  
  _impl_.err_desc_.Set(value, GetArenaForAllocation());
}
inline std::string* Add_Response::_internal_mutable_err_desc() {
  
  return _impl_.err_desc_.Mutable(GetArenaForAllocation());
}
inline std::string* Add_Response::release_err_desc() {
  // @@protoc_insertion_point(field_release:contact.Add_Response.err_desc)
  return _impl_.err_desc_.Release();
}
inline void Add_Response::set_allocated_err_desc(std::string* err_desc) {
  if (err_desc != nullptr) {
    
  } else {
    
  }
  _impl_.err_desc_.SetAllocated(err_desc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.err_desc_.IsDefault()) {
    _impl_.err_desc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contact.Add_Response.err_desc)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace contact

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::contact::Add_Request_Phone_PhoneType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::contact::Add_Request_Phone_PhoneType>() {
  return ::contact::Add_Request_Phone_PhoneType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_contact_2eproto
