// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_contact_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_contact_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_contact_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_contact_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_contact_2eproto;
namespace contact {
class Add_Request;
class Add_RequestDefaultTypeInternal;
extern Add_RequestDefaultTypeInternal _Add_Request_default_instance_;
class Add_Request_Phone;
class Add_Request_PhoneDefaultTypeInternal;
extern Add_Request_PhoneDefaultTypeInternal _Add_Request_Phone_default_instance_;
class Add_Response;
class Add_ResponseDefaultTypeInternal;
extern Add_ResponseDefaultTypeInternal _Add_Response_default_instance_;
}  // namespace contact
PROTOBUF_NAMESPACE_OPEN
template<> ::contact::Add_Request* Arena::CreateMaybeMessage<::contact::Add_Request>(Arena*);
template<> ::contact::Add_Request_Phone* Arena::CreateMaybeMessage<::contact::Add_Request_Phone>(Arena*);
template<> ::contact::Add_Response* Arena::CreateMaybeMessage<::contact::Add_Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace contact {

enum Add_Request_Phone_PhoneType : int {
  Add_Request_Phone_PhoneType_Mobile_Phone = 0,
  Add_Request_Phone_PhoneType_TELEPHONE = 1,
  Add_Request_Phone_PhoneType_Add_Request_Phone_PhoneType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Add_Request_Phone_PhoneType_Add_Request_Phone_PhoneType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Add_Request_Phone_PhoneType_IsValid(int value);
constexpr Add_Request_Phone_PhoneType Add_Request_Phone_PhoneType_PhoneType_MIN = Add_Request_Phone_PhoneType_Mobile_Phone;
constexpr Add_Request_Phone_PhoneType Add_Request_Phone_PhoneType_PhoneType_MAX = Add_Request_Phone_PhoneType_TELEPHONE;
constexpr int Add_Request_Phone_PhoneType_PhoneType_ARRAYSIZE = Add_Request_Phone_PhoneType_PhoneType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Add_Request_Phone_PhoneType_descriptor();
template<typename T>
inline const std::string& Add_Request_Phone_PhoneType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Add_Request_Phone_PhoneType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Add_Request_Phone_PhoneType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Add_Request_Phone_PhoneType_descriptor(), enum_t_value);
}
inline bool Add_Request_Phone_PhoneType_Parse(
    const std::string& name, Add_Request_Phone_PhoneType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Add_Request_Phone_PhoneType>(
    Add_Request_Phone_PhoneType_descriptor(), name, value);
}
// ===================================================================

class Add_Request_Phone PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contact.Add_Request.Phone) */ {
 public:
  inline Add_Request_Phone() : Add_Request_Phone(nullptr) {};
  virtual ~Add_Request_Phone();

  Add_Request_Phone(const Add_Request_Phone& from);
  Add_Request_Phone(Add_Request_Phone&& from) noexcept
    : Add_Request_Phone() {
    *this = ::std::move(from);
  }

  inline Add_Request_Phone& operator=(const Add_Request_Phone& from) {
    CopyFrom(from);
    return *this;
  }
  inline Add_Request_Phone& operator=(Add_Request_Phone&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Add_Request_Phone& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Add_Request_Phone* internal_default_instance() {
    return reinterpret_cast<const Add_Request_Phone*>(
               &_Add_Request_Phone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Add_Request_Phone& a, Add_Request_Phone& b) {
    a.Swap(&b);
  }
  inline void Swap(Add_Request_Phone* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Add_Request_Phone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Add_Request_Phone* New() const final {
    return CreateMaybeMessage<Add_Request_Phone>(nullptr);
  }

  Add_Request_Phone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Add_Request_Phone>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Add_Request_Phone& from);
  void MergeFrom(const Add_Request_Phone& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Add_Request_Phone* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contact.Add_Request.Phone";
  }
  protected:
  explicit Add_Request_Phone(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_contact_2eproto);
    return ::descriptor_table_contact_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Add_Request_Phone_PhoneType PhoneType;
  static constexpr PhoneType Mobile_Phone =
    Add_Request_Phone_PhoneType_Mobile_Phone;
  static constexpr PhoneType TELEPHONE =
    Add_Request_Phone_PhoneType_TELEPHONE;
  static inline bool PhoneType_IsValid(int value) {
    return Add_Request_Phone_PhoneType_IsValid(value);
  }
  static constexpr PhoneType PhoneType_MIN =
    Add_Request_Phone_PhoneType_PhoneType_MIN;
  static constexpr PhoneType PhoneType_MAX =
    Add_Request_Phone_PhoneType_PhoneType_MAX;
  static constexpr int PhoneType_ARRAYSIZE =
    Add_Request_Phone_PhoneType_PhoneType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  PhoneType_descriptor() {
    return Add_Request_Phone_PhoneType_descriptor();
  }
  template<typename T>
  static inline const std::string& PhoneType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PhoneType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PhoneType_Name.");
    return Add_Request_Phone_PhoneType_Name(enum_t_value);
  }
  static inline bool PhoneType_Parse(const std::string& name,
      PhoneType* value) {
    return Add_Request_Phone_PhoneType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kNumberFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string number = 1;
  void clear_number();
  const std::string& number() const;
  void set_number(const std::string& value);
  void set_number(std::string&& value);
  void set_number(const char* value);
  void set_number(const char* value, size_t size);
  std::string* mutable_number();
  std::string* release_number();
  void set_allocated_number(std::string* number);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_number();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_number(
      std::string* number);
  private:
  const std::string& _internal_number() const;
  void _internal_set_number(const std::string& value);
  std::string* _internal_mutable_number();
  public:

  // .contact.Add_Request.Phone.PhoneType type = 2;
  void clear_type();
  ::contact::Add_Request_Phone_PhoneType type() const;
  void set_type(::contact::Add_Request_Phone_PhoneType value);
  private:
  ::contact::Add_Request_Phone_PhoneType _internal_type() const;
  void _internal_set_type(::contact::Add_Request_Phone_PhoneType value);
  public:

  // @@protoc_insertion_point(class_scope:contact.Add_Request.Phone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr number_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_contact_2eproto;
};
// -------------------------------------------------------------------

class Add_Request PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contact.Add_Request) */ {
 public:
  inline Add_Request() : Add_Request(nullptr) {};
  virtual ~Add_Request();

  Add_Request(const Add_Request& from);
  Add_Request(Add_Request&& from) noexcept
    : Add_Request() {
    *this = ::std::move(from);
  }

  inline Add_Request& operator=(const Add_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Add_Request& operator=(Add_Request&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Add_Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Add_Request* internal_default_instance() {
    return reinterpret_cast<const Add_Request*>(
               &_Add_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Add_Request& a, Add_Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Add_Request* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Add_Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Add_Request* New() const final {
    return CreateMaybeMessage<Add_Request>(nullptr);
  }

  Add_Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Add_Request>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Add_Request& from);
  void MergeFrom(const Add_Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Add_Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contact.Add_Request";
  }
  protected:
  explicit Add_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_contact_2eproto);
    return ::descriptor_table_contact_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Add_Request_Phone Phone;

  // accessors -------------------------------------------------------

  enum : int {
    kPhoneNumbsersFieldNumber = 3,
    kNameFieldNumber = 1,
    kAgeFieldNumber = 2,
  };
  // repeated .contact.Add_Request.Phone phone_numbsers = 3;
  int phone_numbsers_size() const;
  private:
  int _internal_phone_numbsers_size() const;
  public:
  void clear_phone_numbsers();
  ::contact::Add_Request_Phone* mutable_phone_numbsers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone >*
      mutable_phone_numbsers();
  private:
  const ::contact::Add_Request_Phone& _internal_phone_numbsers(int index) const;
  ::contact::Add_Request_Phone* _internal_add_phone_numbsers();
  public:
  const ::contact::Add_Request_Phone& phone_numbsers(int index) const;
  ::contact::Add_Request_Phone* add_phone_numbsers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone >&
      phone_numbsers() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 age = 2;
  void clear_age();
  ::PROTOBUF_NAMESPACE_ID::int32 age() const;
  void set_age(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_age() const;
  void _internal_set_age(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:contact.Add_Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone > phone_numbsers_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::int32 age_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_contact_2eproto;
};
// -------------------------------------------------------------------

class Add_Response PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contact.Add_Response) */ {
 public:
  inline Add_Response() : Add_Response(nullptr) {};
  virtual ~Add_Response();

  Add_Response(const Add_Response& from);
  Add_Response(Add_Response&& from) noexcept
    : Add_Response() {
    *this = ::std::move(from);
  }

  inline Add_Response& operator=(const Add_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Add_Response& operator=(Add_Response&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Add_Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Add_Response* internal_default_instance() {
    return reinterpret_cast<const Add_Response*>(
               &_Add_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Add_Response& a, Add_Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Add_Response* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Add_Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Add_Response* New() const final {
    return CreateMaybeMessage<Add_Response>(nullptr);
  }

  Add_Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Add_Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Add_Response& from);
  void MergeFrom(const Add_Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Add_Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contact.Add_Response";
  }
  protected:
  explicit Add_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_contact_2eproto);
    return ::descriptor_table_contact_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kErrDescFieldNumber = 3,
    kOkFieldNumber = 2,
  };
  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  void set_uuid(const std::string& value);
  void set_uuid(std::string&& value);
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  std::string* mutable_uuid();
  std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_uuid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_uuid(
      std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // string err_desc = 3;
  void clear_err_desc();
  const std::string& err_desc() const;
  void set_err_desc(const std::string& value);
  void set_err_desc(std::string&& value);
  void set_err_desc(const char* value);
  void set_err_desc(const char* value, size_t size);
  std::string* mutable_err_desc();
  std::string* release_err_desc();
  void set_allocated_err_desc(std::string* err_desc);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_err_desc();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_err_desc(
      std::string* err_desc);
  private:
  const std::string& _internal_err_desc() const;
  void _internal_set_err_desc(const std::string& value);
  std::string* _internal_mutable_err_desc();
  public:

  // bool ok = 2;
  void clear_ok();
  bool ok() const;
  void set_ok(bool value);
  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);
  public:

  // @@protoc_insertion_point(class_scope:contact.Add_Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr err_desc_;
  bool ok_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_contact_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Add_Request_Phone

// string number = 1;
inline void Add_Request_Phone::clear_number() {
  number_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Add_Request_Phone::number() const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.Phone.number)
  return _internal_number();
}
inline void Add_Request_Phone::set_number(const std::string& value) {
  _internal_set_number(value);
  // @@protoc_insertion_point(field_set:contact.Add_Request.Phone.number)
}
inline std::string* Add_Request_Phone::mutable_number() {
  // @@protoc_insertion_point(field_mutable:contact.Add_Request.Phone.number)
  return _internal_mutable_number();
}
inline const std::string& Add_Request_Phone::_internal_number() const {
  return number_.Get();
}
inline void Add_Request_Phone::_internal_set_number(const std::string& value) {
  
  number_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Add_Request_Phone::set_number(std::string&& value) {
  
  number_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:contact.Add_Request.Phone.number)
}
inline void Add_Request_Phone::set_number(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  number_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:contact.Add_Request.Phone.number)
}
inline void Add_Request_Phone::set_number(const char* value,
    size_t size) {
  
  number_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:contact.Add_Request.Phone.number)
}
inline std::string* Add_Request_Phone::_internal_mutable_number() {
  
  return number_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Add_Request_Phone::release_number() {
  // @@protoc_insertion_point(field_release:contact.Add_Request.Phone.number)
  return number_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Add_Request_Phone::set_allocated_number(std::string* number) {
  if (number != nullptr) {
    
  } else {
    
  }
  number_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), number,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:contact.Add_Request.Phone.number)
}
inline std::string* Add_Request_Phone::unsafe_arena_release_number() {
  // @@protoc_insertion_point(field_unsafe_arena_release:contact.Add_Request.Phone.number)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return number_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Add_Request_Phone::unsafe_arena_set_allocated_number(
    std::string* number) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (number != nullptr) {
    
  } else {
    
  }
  number_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      number, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:contact.Add_Request.Phone.number)
}

// .contact.Add_Request.Phone.PhoneType type = 2;
inline void Add_Request_Phone::clear_type() {
  type_ = 0;
}
inline ::contact::Add_Request_Phone_PhoneType Add_Request_Phone::_internal_type() const {
  return static_cast< ::contact::Add_Request_Phone_PhoneType >(type_);
}
inline ::contact::Add_Request_Phone_PhoneType Add_Request_Phone::type() const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.Phone.type)
  return _internal_type();
}
inline void Add_Request_Phone::_internal_set_type(::contact::Add_Request_Phone_PhoneType value) {
  
  type_ = value;
}
inline void Add_Request_Phone::set_type(::contact::Add_Request_Phone_PhoneType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:contact.Add_Request.Phone.type)
}

// -------------------------------------------------------------------

// Add_Request

// string name = 1;
inline void Add_Request::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Add_Request::name() const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.name)
  return _internal_name();
}
inline void Add_Request::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:contact.Add_Request.name)
}
inline std::string* Add_Request::mutable_name() {
  // @@protoc_insertion_point(field_mutable:contact.Add_Request.name)
  return _internal_mutable_name();
}
inline const std::string& Add_Request::_internal_name() const {
  return name_.Get();
}
inline void Add_Request::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Add_Request::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:contact.Add_Request.name)
}
inline void Add_Request::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:contact.Add_Request.name)
}
inline void Add_Request::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:contact.Add_Request.name)
}
inline std::string* Add_Request::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Add_Request::release_name() {
  // @@protoc_insertion_point(field_release:contact.Add_Request.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Add_Request::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:contact.Add_Request.name)
}
inline std::string* Add_Request::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:contact.Add_Request.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Add_Request::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:contact.Add_Request.name)
}

// int32 age = 2;
inline void Add_Request::clear_age() {
  age_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Add_Request::_internal_age() const {
  return age_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Add_Request::age() const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.age)
  return _internal_age();
}
inline void Add_Request::_internal_set_age(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  age_ = value;
}
inline void Add_Request::set_age(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:contact.Add_Request.age)
}

// repeated .contact.Add_Request.Phone phone_numbsers = 3;
inline int Add_Request::_internal_phone_numbsers_size() const {
  return phone_numbsers_.size();
}
inline int Add_Request::phone_numbsers_size() const {
  return _internal_phone_numbsers_size();
}
inline void Add_Request::clear_phone_numbsers() {
  phone_numbsers_.Clear();
}
inline ::contact::Add_Request_Phone* Add_Request::mutable_phone_numbsers(int index) {
  // @@protoc_insertion_point(field_mutable:contact.Add_Request.phone_numbsers)
  return phone_numbsers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone >*
Add_Request::mutable_phone_numbsers() {
  // @@protoc_insertion_point(field_mutable_list:contact.Add_Request.phone_numbsers)
  return &phone_numbsers_;
}
inline const ::contact::Add_Request_Phone& Add_Request::_internal_phone_numbsers(int index) const {
  return phone_numbsers_.Get(index);
}
inline const ::contact::Add_Request_Phone& Add_Request::phone_numbsers(int index) const {
  // @@protoc_insertion_point(field_get:contact.Add_Request.phone_numbsers)
  return _internal_phone_numbsers(index);
}
inline ::contact::Add_Request_Phone* Add_Request::_internal_add_phone_numbsers() {
  return phone_numbsers_.Add();
}
inline ::contact::Add_Request_Phone* Add_Request::add_phone_numbsers() {
  // @@protoc_insertion_point(field_add:contact.Add_Request.phone_numbsers)
  return _internal_add_phone_numbsers();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contact::Add_Request_Phone >&
Add_Request::phone_numbsers() const {
  // @@protoc_insertion_point(field_list:contact.Add_Request.phone_numbsers)
  return phone_numbsers_;
}

// -------------------------------------------------------------------

// Add_Response

// string uuid = 1;
inline void Add_Response::clear_uuid() {
  uuid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Add_Response::uuid() const {
  // @@protoc_insertion_point(field_get:contact.Add_Response.uuid)
  return _internal_uuid();
}
inline void Add_Response::set_uuid(const std::string& value) {
  _internal_set_uuid(value);
  // @@protoc_insertion_point(field_set:contact.Add_Response.uuid)
}
inline std::string* Add_Response::mutable_uuid() {
  // @@protoc_insertion_point(field_mutable:contact.Add_Response.uuid)
  return _internal_mutable_uuid();
}
inline const std::string& Add_Response::_internal_uuid() const {
  return uuid_.Get();
}
inline void Add_Response::_internal_set_uuid(const std::string& value) {
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Add_Response::set_uuid(std::string&& value) {
  
  uuid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:contact.Add_Response.uuid)
}
inline void Add_Response::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:contact.Add_Response.uuid)
}
inline void Add_Response::set_uuid(const char* value,
    size_t size) {
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:contact.Add_Response.uuid)
}
inline std::string* Add_Response::_internal_mutable_uuid() {
  
  return uuid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Add_Response::release_uuid() {
  // @@protoc_insertion_point(field_release:contact.Add_Response.uuid)
  return uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Add_Response::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uuid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:contact.Add_Response.uuid)
}
inline std::string* Add_Response::unsafe_arena_release_uuid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:contact.Add_Response.uuid)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return uuid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Add_Response::unsafe_arena_set_allocated_uuid(
    std::string* uuid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      uuid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:contact.Add_Response.uuid)
}

// bool ok = 2;
inline void Add_Response::clear_ok() {
  ok_ = false;
}
inline bool Add_Response::_internal_ok() const {
  return ok_;
}
inline bool Add_Response::ok() const {
  // @@protoc_insertion_point(field_get:contact.Add_Response.ok)
  return _internal_ok();
}
inline void Add_Response::_internal_set_ok(bool value) {
  
  ok_ = value;
}
inline void Add_Response::set_ok(bool value) {
  _internal_set_ok(value);
  // @@protoc_insertion_point(field_set:contact.Add_Response.ok)
}

// string err_desc = 3;
inline void Add_Response::clear_err_desc() {
  err_desc_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Add_Response::err_desc() const {
  // @@protoc_insertion_point(field_get:contact.Add_Response.err_desc)
  return _internal_err_desc();
}
inline void Add_Response::set_err_desc(const std::string& value) {
  _internal_set_err_desc(value);
  // @@protoc_insertion_point(field_set:contact.Add_Response.err_desc)
}
inline std::string* Add_Response::mutable_err_desc() {
  // @@protoc_insertion_point(field_mutable:contact.Add_Response.err_desc)
  return _internal_mutable_err_desc();
}
inline const std::string& Add_Response::_internal_err_desc() const {
  return err_desc_.Get();
}
inline void Add_Response::_internal_set_err_desc(const std::string& value) {
  
  err_desc_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Add_Response::set_err_desc(std::string&& value) {
  
  err_desc_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:contact.Add_Response.err_desc)
}
inline void Add_Response::set_err_desc(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  err_desc_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:contact.Add_Response.err_desc)
}
inline void Add_Response::set_err_desc(const char* value,
    size_t size) {
  
  err_desc_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:contact.Add_Response.err_desc)
}
inline std::string* Add_Response::_internal_mutable_err_desc() {
  
  return err_desc_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Add_Response::release_err_desc() {
  // @@protoc_insertion_point(field_release:contact.Add_Response.err_desc)
  return err_desc_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Add_Response::set_allocated_err_desc(std::string* err_desc) {
  if (err_desc != nullptr) {
    
  } else {
    
  }
  err_desc_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), err_desc,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:contact.Add_Response.err_desc)
}
inline std::string* Add_Response::unsafe_arena_release_err_desc() {
  // @@protoc_insertion_point(field_unsafe_arena_release:contact.Add_Response.err_desc)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return err_desc_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Add_Response::unsafe_arena_set_allocated_err_desc(
    std::string* err_desc) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (err_desc != nullptr) {
    
  } else {
    
  }
  err_desc_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      err_desc, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:contact.Add_Response.err_desc)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace contact

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::contact::Add_Request_Phone_PhoneType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::contact::Add_Request_Phone_PhoneType>() {
  return ::contact::Add_Request_Phone_PhoneType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_contact_2eproto
